improve error handling
Mintbase/minsta pull request #66
Opened 2023-12-05 00:30 UTC by rubenmarcus

2023-12-05 00:31 UTC, rubenmarcus commented on src/data/queries/feed.graphl.ts
> +    mintbase
this should be removed, it was added just to simulate the error

2023-12-05 02:18 UTC, rubenmarcus commented on src/data/queries/feed.graphl.ts
> +      mintbase
this should be removed, it was added just to emulate the error

2023-12-06 15:07 UTC, sainthiago requested changes

2023-12-06 16:26 UTC, rubenmarcus commented on src/components/feed/feedscroll.tsx
> +        Error. <br/> Please contact Mintbase Team at{" "}
added

2023-12-11 11:21 UTC, sainthiago approved these changes

2023-12-11 11:48 UTC, merged